version: 2

sources:
  - name: raw_data
    description: Raw data from PostgreSQL database
    tables:
      - name: orders
        description: Customer orders table
        columns:
          - name: order_id
            description: Unique identifier for each order
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Reference to customer
            tests:
              - not_null
          - name: order_date
            description: Date when order was placed
            tests:
              - not_null
          - name: total_amount
            description: Total order amount
            tests:
              - not_null

      - name: customers
        description: Customer information table
        columns:
          - name: customer_id
            description: Unique identifier for each customer
            tests:
              - unique
              - not_null
          - name: email
            description: Customer email address
            tests:
              - unique
              - not_null

      - name: products
        description: Product catalog table
        columns:
          - name: product_id
            description: Unique identifier for each product
            tests:
              - unique
              - not_null
          - name: product_name
            description: Name of the product
            tests:
              - not_null